services:
  - type: web
    name: nym-shipment-tracker
    env: python
    plan: professional
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn shipment_tracking_system_v2.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: shipment_tracking_system.settings
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: RENDER_EXTERNAL_HOSTNAME
        value: your-custom-domain.com
      - key: MAILGUN_API_KEY
        fromSecret: true
      - key: MAILGUN_DOMAIN
        fromSecret: true
      - key: TWILIO_ACCOUNT_SID
        fromSecret: true
      - key: TWILIO_AUTH_TOKEN
        fromSecret: true
      - key: TWILIO_WHATSAPP_FROM
        fromSecret: true
      - key: DATABASE_URL
        fromDatabase:
          name: nym-shipment-tracker-db
          property: connectionString

databases:
  - name: nym-shipment-tracker-db
    databaseName: nym_shipment_tracker_db
    user: nym_shipment_tracker_user
    plan: professional
    postgresMajorVersion: 14
