# Generated by Django 5.2 on 2025-04-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentcustomer',
            name='email',
            field=models.EmailField(default='noemail@naiyuanmart.com', max_length=254),
            preserve_default=False,
        ),
    ]
