# Generated by Django 5.2 on 2025-04-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_shipmentcustomer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
