# Generated by Django 5.2 on 2025-04-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_segment_subscriber_subscribersegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='sid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
